# Generated by Django 5.2.4 on 2025-08-02 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('available_classes', models.CharField(help_text='Comma-separated list of available classes', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission notice',
                'verbose_name_plural': 'Admission notices',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhaar_no', models.CharField(max_length=20)),
                ('father_mother_guardian', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('permanent_pincode', models.CharField(max_length=10)),
                ('present_address', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_language', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_conditions', models.CharField(blank=True, max_length=255)),
                ('admission_class', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=20)),
                ('qualification', models.CharField(max_length=255)),
                ('school_college', models.CharField(max_length=255)),
                ('school_college_address', models.CharField(max_length=255)),
                ('reason_for_learning', models.TextField()),
                ('previous_training', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('art_form', models.CharField(max_length=100)),
                ('expertise_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('course_duration_years', models.IntegerField()),
                ('photo_id_attached', models.BooleanField(default=False)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('aadhaar_path', models.FileField(blank=True, null=True, upload_to='students/aadhaar/')),
                ('education_cert_path', models.FileField(blank=True, null=True, upload_to='students/education_certs/')),
                ('medical_fitness_path', models.FileField(blank=True, null=True, upload_to='students/medical_fitness/')),
                ('previous_training_cert', models.FileField(blank=True, null=True, upload_to='students/training_certs/')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status for admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='marksheets/')),
                ('issued_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('event_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
        ),
    ]
