# Generated by Django 5.2.4 on 2025-08-02 03:51

import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhaar_no', models.CharField(max_length=20)),
                ('father_mother_guardian', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('permanent_pincode', models.CharField(max_length=10)),
                ('present_address', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_language', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_conditions', models.CharField(blank=True, max_length=255)),
                ('admission_class', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=20)),
                ('qualification', models.CharField(max_length=255)),
                ('school_college', models.CharField(max_length=255)),
                ('school_college_address', models.CharField(max_length=255)),
                ('reason_for_learning', models.TextField()),
                ('previous_training', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('art_form', models.CharField(max_length=100)),
                ('expertise_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('course_duration_years', models.IntegerField()),
                ('photo_id_attached', models.BooleanField(default=False)),
                ('photo_path', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_upload_to)),
                ('aadhaar_path', models.FileField(blank=True, null=True, upload_to=students.models.aadhaar_upload_to)),
                ('education_cert_path', models.FileField(blank=True, null=True, upload_to=students.models.education_certs_upload_to)),
                ('medical_fitness_path', models.FileField(blank=True, null=True, upload_to=students.models.medical_fitness_upload_to)),
                ('previous_training_cert', models.FileField(blank=True, null=True, upload_to=students.models.training_certs_upload_to)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status for admission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='student',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=students.models.certificate_upload_to),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=students.models.marksheet_upload_to),
        ),
        migrations.AddField(
            model_name='certificate',
            name='admission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksheet',
            name='admission',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='students.admission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.admission'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
