# Generated by Django 5.2.4 on 2025-08-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_admission_user'),
    ]

    operations = [
    ]
