# Generated by Django 5.2.4 on 2025-07-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('gallery', 'Gallery'), ('performance', 'Performance')], max_length=20)),
                ('ref_id', models.IntegerField()),
                ('display_order', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('video_link', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aadhaar_no', models.CharField(max_length=20)),
                ('father_mother_guardian', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('permanent_pincode', models.CharField(max_length=10)),
                ('present_address', models.CharField(max_length=255)),
                ('present_pincode', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_language', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_conditions', models.CharField(blank=True, max_length=255)),
                ('admission_class', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=20)),
                ('qualification', models.CharField(max_length=255)),
                ('school_college', models.CharField(max_length=255)),
                ('school_college_address', models.CharField(max_length=255)),
                ('reason_for_learning', models.TextField()),
                ('previous_training', models.CharField(blank=True, max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('art_form', models.CharField(max_length=100)),
                ('expertise_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('course_duration_years', models.IntegerField()),
                ('photo_id_attached', models.BooleanField(default=False)),
                ('photo_path', models.CharField(blank=True, max_length=255)),
                ('aadhaar_path', models.CharField(blank=True, max_length=255)),
                ('education_cert_path', models.CharField(blank=True, max_length=255)),
                ('medical_fitness_path', models.CharField(blank=True, max_length=255)),
                ('previous_training_cert', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('ballet', 'Ballet'), ('drama', 'Drama')], max_length=50)),
                ('event_date', models.DateField()),
                ('is_upcoming', models.BooleanField(default=False)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallerymedia')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('event_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student')),
            ],
        ),
    ]
