# Generated by Django 5.2.4 on 2025-07-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status for admission'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required for login'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='gallerymedia',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='marksheets/'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='performances/images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhaar_path',
            field=models.FileField(blank=True, null=True, upload_to='students/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_cert_path',
            field=models.FileField(blank=True, null=True, upload_to='students/education_certs/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_fitness_path',
            field=models.FileField(blank=True, null=True, upload_to='students/medical_fitness/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_training_cert',
            field=models.FileField(blank=True, null=True, upload_to='students/training_certs/'),
        ),
    ]
