# Generated by Django 5.2.4 on 2025-07-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_admissionnotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionnotice',
            options={'verbose_name': 'Admission notice', 'verbose_name_plural': 'Admission notices'},
        ),
    ]
