# Generated by Django 5.2.4 on 2025-07-31 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_admissionnotice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aboutus')),
            ],
        ),
    ]
