# Generated by Django 5.2.4 on 2025-07-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutusimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='image_path',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image_path',
        ),
        migrations.AddField(
            model_name='performance',
            name='venue',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Link to gallery for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallerymedia'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Check if this is an upcoming event. Uncheck for past events.'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
