# Generated by Django 5.2.4 on 2025-08-02 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_guru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusimage',
            name='about',
        ),
        migrations.DeleteModel(
            name='AdmissionNotice',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Guru',
        ),
        migrations.DeleteModel(
            name='HomepageHighlight',
        ),
        migrations.DeleteModel(
            name='HomepageSection',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsImage',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='GalleryMedia',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
