# Generated by Django 5.2.4 on 2025-08-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallerymedia_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
