# Generated by Django 5.2.4 on 2025-08-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallerymedia_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='is_deleted',
        ),
    ]
