# Generated by Django 5.2.4 on 2025-08-02 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('is_upcoming', models.BooleanField(default=False, help_text='Check if this is an upcoming event. Uncheck for past events.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='performances/images/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('gallery', models.ForeignKey(blank=True, help_text='Link to gallery for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallerymedia')),
            ],
        ),
    ]
