# Generated by Django 5.2.4 on 2025-08-02 03:51

import performances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=performances.models.performance_image_upload_to),
        ),
    ]
