# Generated by Django 5.2.4 on 2025-08-02 03:51

import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.testimonial_image_upload_to),
        ),
    ]
