# Generated by Django 5.2.4 on 2025-08-02 03:51

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusimage',
            name='image',
            field=models.ImageField(upload_to=about.models.aboutus_image_upload_to),
        ),
        migrations.AlterField(
            model_name='guru',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.guru_photo_upload_to),
        ),
    ]
