# Generated by Django 5.2.4 on 2025-08-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutusimage_image_alter_guru_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
